import { useCallback } from 'react';
import { useAuth } from './context/AuthContext';

const en = {
  'nav.explore': 'Explore', 'nav.community': 'Community', 'nav.trips': 'Trips', 'nav.inbox': 'Inbox', 'nav.profile': 'Profile',
  'welcome.title': 'Explore Mongolia\nwith local eyes', 'welcome.sub': 'Discover authentic places and travel with trusted local guides.', 'welcome.travel': 'Travel', 'welcome.travelSub': 'Find stays, experiences and local guides', 'welcome.guide': 'Be a guide', 'welcome.guideSub': 'Share your culture and earn with VenTour',
  'auth.create': 'Create account', 'auth.welcome': 'Welcome back', 'auth.guide': 'Sign in as a local guide', 'auth.traveler': 'Continue as a traveler', 'auth.name': 'Name', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.register': 'Register', 'auth.login': 'Log in', 'auth.hasAccount': 'Already have an account? Log in', 'auth.new': 'New here? Create account',
  'profile.title': 'Profile', 'profile.signInCopy': 'Sign in to manage your trips and guides.', 'profile.login': 'Log in', 'profile.create': 'Create account', 'profile.account': 'Account settings', 'profile.saved': 'Saved trips', 'profile.payment': 'Payment', 'profile.help': 'Help center', 'profile.safety': 'Safety and emergency', 'profile.becomeGuide': 'Become a guide', 'profile.guideWorkspace': 'Guide workspace', 'profile.ranking': 'Guide ranking', 'profile.logout': 'Log out',
  'booking.title': 'Booking request', 'booking.review': 'The provider will review your date and request before confirmation.', 'booking.date': 'Date (YYYY-MM-DD)', 'booking.time': 'Start time (24-hour)', 'booking.hours': 'Hours', 'booking.nights': 'Nights', 'booking.guests': 'Guests', 'booking.notes': 'Notes for the provider (optional)', 'booking.notesHint': 'Pickup needs, dietary or accessibility requirements', 'booking.rate': 'Rate', 'booking.total': 'Estimated total', 'booking.pilot': 'Pay on arrival during the pilot. Do not send card details in chat.', 'booking.send': 'Send booking request', 'booking.check': 'Check booking details', 'booking.checkBody': 'Use a future date, 24-hour time, and values between 1 and 30.', 'booking.sent': 'Request sent', 'booking.sentBody': 'The provider must accept before your booking is confirmed.', 'booking.failed': 'Booking failed', 'booking.cancellation': 'Cancellation policy', 'booking.cancellationBody': 'Free cancellation until 24 hours before the start. Later traveler cancellations may incur 20% of the booking total.',
  'trips.title': 'Trips', 'trips.loginCopy': 'Log in to see your bookings.', 'trips.empty': 'No trips yet. Send a request from Explore or Guides.', 'trips.cancel': 'Cancel booking', 'trips.cancelTitle': 'Cancel booking?', 'trips.cancelBody': 'The provider will be notified.', 'trips.keep': 'Keep booking', 'trips.cancelFailed': 'Could not cancel', 'trips.dateMissing': 'Date unavailable',
  'payment.title': 'Payment', 'payment.arrival': 'Pay on arrival', 'payment.arrivalBody': 'Card payments are not enabled during the pilot. Agree on the payment method only after the provider accepts your booking.', 'payment.protect': 'Protect your payment details', 'payment.protectBody': 'VenTour will never ask you to send a card number, password, or verification code in chat.',
  'safety.title': 'Safety and emergency', 'safety.copy': 'Save these numbers before traveling outside Ulaanbaatar. Calls use Mongolia emergency services.', 'safety.fire': 'Fire', 'safety.police': 'Police', 'safety.ambulance': 'Ambulance', 'safety.call': 'Call', 'safety.offline': 'Available offline', 'safety.trip': 'Share your itinerary and provider contact with someone you trust. Connectivity and emergency response can be limited outside major cities.',
  'common.back': 'Go back', 'common.cached': 'Showing saved results. Some information may be outdated.',
};

const mn = {
  'nav.explore': 'Аялах', 'nav.community': 'Нийгэмлэг', 'nav.trips': 'Захиалга', 'nav.inbox': 'Мессеж', 'nav.profile': 'Профайл',
  'welcome.title': 'Монголыг нутгийн хүний\nнүдээр нээгээрэй', 'welcome.sub': 'Онцгой газруудыг олж, баталгаажсан нутгийн хөтөчтэй аялаарай.', 'welcome.travel': 'Аялагч', 'welcome.travelSub': 'Байр, аяллын туршлага, нутгийн хөтөч олох', 'welcome.guide': 'Хөтөч болох', 'welcome.guideSub': 'Соёлоо хуваалцаж, VenTour-оор орлого олох',
  'auth.create': 'Бүртгэл үүсгэх', 'auth.welcome': 'Тавтай морил', 'auth.guide': 'Нутгийн хөтөчөөр нэвтрэх', 'auth.traveler': 'Аялагчаар үргэлжлүүлэх', 'auth.name': 'Нэр', 'auth.email': 'Имэйл', 'auth.password': 'Нууц үг', 'auth.register': 'Бүртгүүлэх', 'auth.login': 'Нэвтрэх', 'auth.hasAccount': 'Бүртгэлтэй юу? Нэвтрэх', 'auth.new': 'Шинэ хэрэглэгч үү? Бүртгүүлэх',
  'profile.title': 'Профайл', 'profile.signInCopy': 'Захиалга, хөтчөө удирдахын тулд нэвтэрнэ үү.', 'profile.login': 'Нэвтрэх', 'profile.create': 'Бүртгэл үүсгэх', 'profile.account': 'Бүртгэлийн тохиргоо', 'profile.saved': 'Хадгалсан аялал', 'profile.payment': 'Төлбөр', 'profile.help': 'Тусламж', 'profile.safety': 'Аюулгүй байдал', 'profile.becomeGuide': 'Хөтөч болох', 'profile.guideWorkspace': 'Хөтчийн хэсэг', 'profile.ranking': 'Хөтчийн үнэлгээ', 'profile.logout': 'Гарах',
  'booking.title': 'Захиалгын хүсэлт', 'booking.review': 'Үйлчилгээ үзүүлэгч огноо, хүсэлтийг шалгасны дараа баталгаажуулна.', 'booking.date': 'Огноо (ЖЖЖЖ-СС-ӨӨ)', 'booking.time': 'Эхлэх цаг (24 цаг)', 'booking.hours': 'Цаг', 'booking.nights': 'Хоног', 'booking.guests': 'Хүний тоо', 'booking.notes': 'Нэмэлт хүсэлт', 'booking.notesHint': 'Тосох газар, хоол, хүртээмжийн хэрэгцээ', 'booking.rate': 'Тариф', 'booking.total': 'Тооцоолсон нийт үнэ', 'booking.pilot': 'Туршилтын үед очоод төлнө. Картын мэдээллээ чатаар бүү илгээнэ үү.', 'booking.send': 'Захиалгын хүсэлт илгээх', 'booking.check': 'Мэдээллээ шалгана уу', 'booking.checkBody': 'Ирээдүйн огноо, 24 цагийн цаг болон 1-30 хооронд утга оруулна уу.', 'booking.sent': 'Хүсэлт илгээгдлээ', 'booking.sentBody': 'Үйлчилгээ үзүүлэгч зөвшөөрсний дараа захиалга баталгаажна.', 'booking.failed': 'Захиалга амжилтгүй', 'booking.cancellation': 'Цуцлалтын нөхцөл', 'booking.cancellationBody': 'Эхлэхээс 24 цагийн өмнө үнэгүй цуцална. Үүнээс хойш аялагч цуцалбал нийт үнийн 20% хүртэл шимтгэлтэй.',
  'trips.title': 'Захиалга', 'trips.loginCopy': 'Захиалгаа харахын тулд нэвтэрнэ үү.', 'trips.empty': 'Захиалга алга. Аялах эсвэл Хөтөч хэсгээс хүсэлт илгээнэ үү.', 'trips.cancel': 'Захиалга цуцлах', 'trips.cancelTitle': 'Захиалгыг цуцлах уу?', 'trips.cancelBody': 'Үйлчилгээ үзүүлэгчид мэдэгдэнэ.', 'trips.keep': 'Хэвээр үлдээх', 'trips.cancelFailed': 'Цуцалж чадсангүй', 'trips.dateMissing': 'Огноо тодорхойгүй',
  'payment.title': 'Төлбөр', 'payment.arrival': 'Очиж төлөх', 'payment.arrivalBody': 'Туршилтын үед картын төлбөр идэвхгүй. Үйлчилгээ үзүүлэгч захиалгыг зөвшөөрсний дараа төлбөрийн аргаа тохирно уу.', 'payment.protect': 'Төлбөрийн мэдээллээ хамгаалаарай', 'payment.protectBody': 'VenTour чатаар картын дугаар, нууц үг, баталгаажуулах код хэзээ ч асуухгүй.',
  'safety.title': 'Аюулгүй байдал', 'safety.copy': 'Улаанбаатараас гарахын өмнө эдгээр дугаарыг хадгална уу.', 'safety.fire': 'Гал түймэр', 'safety.police': 'Цагдаа', 'safety.ambulance': 'Түргэн тусламж', 'safety.call': 'Залгах', 'safety.offline': 'Интернетгүй үед ажиллана', 'safety.trip': 'Маршрут болон үйлчилгээ үзүүлэгчийн холбоог итгэлтэй хүндээ хуваалцаарай. Хотоос гадна холбоо, тусламж удаашрах боломжтой.',
  'common.back': 'Буцах', 'common.cached': 'Хадгалсан үр дүнг харуулж байна. Зарим мэдээлэл хуучирсан байж болно.',
};

const ru = {
  'nav.explore': 'Обзор', 'nav.community': 'Сообщество', 'nav.trips': 'Поездки', 'nav.inbox': 'Сообщения', 'nav.profile': 'Профиль', 'welcome.title': 'Откройте Монголию\nглазами местных', 'welcome.sub': 'Находите аутентичные места и путешествуйте с проверенными местными гидами.', 'welcome.travel': 'Путешествовать', 'welcome.travelSub': 'Жилье, впечатления и местные гиды', 'welcome.guide': 'Стать гидом', 'welcome.guideSub': 'Делитесь культурой и зарабатывайте с VenTour',
  'auth.create': 'Создать аккаунт', 'auth.welcome': 'С возвращением', 'auth.guide': 'Войти как местный гид', 'auth.traveler': 'Продолжить как путешественник', 'auth.name': 'Имя', 'auth.email': 'Эл. почта', 'auth.password': 'Пароль', 'auth.register': 'Регистрация', 'auth.login': 'Войти', 'auth.hasAccount': 'Уже есть аккаунт? Войти', 'auth.new': 'Впервые здесь? Создать аккаунт',
  'profile.title': 'Профиль', 'profile.signInCopy': 'Войдите, чтобы управлять поездками и гидами.', 'profile.login': 'Войти', 'profile.create': 'Создать аккаунт', 'profile.account': 'Настройки аккаунта', 'profile.saved': 'Сохраненные поездки', 'profile.payment': 'Оплата', 'profile.help': 'Помощь', 'profile.safety': 'Безопасность', 'profile.becomeGuide': 'Стать гидом', 'profile.guideWorkspace': 'Кабинет гида', 'profile.ranking': 'Рейтинг гидов', 'profile.logout': 'Выйти',
  'booking.title': 'Запрос на бронирование', 'booking.review': 'Поставщик проверит дату и запрос до подтверждения.', 'booking.date': 'Дата (ГГГГ-ММ-ДД)', 'booking.time': 'Время начала (24 часа)', 'booking.hours': 'Часы', 'booking.nights': 'Ночи', 'booking.guests': 'Гости', 'booking.notes': 'Пожелания (необязательно)', 'booking.notesHint': 'Трансфер, питание или доступность', 'booking.rate': 'Тариф', 'booking.total': 'Примерная сумма', 'booking.pilot': 'Во время пилота оплата на месте. Не отправляйте данные карты в чате.', 'booking.send': 'Отправить запрос', 'booking.check': 'Проверьте данные', 'booking.checkBody': 'Укажите будущую дату, время и значения от 1 до 30.', 'booking.sent': 'Запрос отправлен', 'booking.sentBody': 'Бронирование подтвердится после согласия поставщика.', 'booking.failed': 'Ошибка бронирования',
  'trips.title': 'Поездки', 'trips.loginCopy': 'Войдите, чтобы увидеть бронирования.', 'trips.empty': 'Бронирований пока нет.', 'trips.cancel': 'Отменить', 'trips.cancelTitle': 'Отменить бронирование?', 'trips.cancelBody': 'Поставщик получит уведомление.', 'trips.keep': 'Не отменять', 'trips.cancelFailed': 'Не удалось отменить', 'trips.dateMissing': 'Дата недоступна',
  'payment.title': 'Оплата', 'payment.arrival': 'Оплата на месте', 'payment.arrivalBody': 'Оплата картой недоступна во время пилота. Согласуйте способ после принятия бронирования.', 'payment.protect': 'Защитите платежные данные', 'payment.protectBody': 'VenTour никогда не просит номер карты, пароль или код в чате.', 'safety.title': 'Безопасность', 'safety.copy': 'Сохраните номера перед поездкой за пределы Улан-Батора.', 'safety.fire': 'Пожарная', 'safety.police': 'Полиция', 'safety.ambulance': 'Скорая', 'safety.call': 'Позвонить', 'safety.offline': 'Доступно офлайн', 'safety.trip': 'Поделитесь маршрутом и контактом гида с близким человеком.', 'common.back': 'Назад', 'common.cached': 'Показаны сохраненные данные. Они могут быть устаревшими.',
};

const zh = {
  'nav.explore': '探索', 'nav.community': '社区', 'nav.trips': '行程', 'nav.inbox': '消息', 'nav.profile': '我的', 'welcome.title': '跟随当地人的视角\n探索蒙古', 'welcome.sub': '发现真实目的地，与可信赖的当地向导同行。', 'welcome.travel': '开始旅行', 'welcome.travelSub': '查找住宿、体验和当地向导', 'welcome.guide': '成为向导', 'welcome.guideSub': '分享文化并通过 VenTour 获得收入',
  'auth.create': '创建账户', 'auth.welcome': '欢迎回来', 'auth.guide': '以当地向导身份登录', 'auth.traveler': '以旅行者身份继续', 'auth.name': '姓名', 'auth.email': '邮箱', 'auth.password': '密码', 'auth.register': '注册', 'auth.login': '登录', 'auth.hasAccount': '已有账户？登录', 'auth.new': '新用户？创建账户',
  'profile.title': '我的', 'profile.signInCopy': '登录后管理行程和向导。', 'profile.login': '登录', 'profile.create': '创建账户', 'profile.account': '账户设置', 'profile.saved': '收藏行程', 'profile.payment': '付款', 'profile.help': '帮助中心', 'profile.safety': '安全与紧急情况', 'profile.becomeGuide': '成为向导', 'profile.guideWorkspace': '向导工作台', 'profile.ranking': '向导排名', 'profile.logout': '退出登录',
  'booking.title': '预订请求', 'booking.review': '服务方确认日期和请求后，预订才会生效。', 'booking.date': '日期（年-月-日）', 'booking.time': '开始时间（24小时）', 'booking.hours': '小时', 'booking.nights': '晚', 'booking.guests': '人数', 'booking.notes': '给服务方的备注（可选）', 'booking.notesHint': '接送、饮食或无障碍需求', 'booking.rate': '单价', 'booking.total': '预计总价', 'booking.pilot': '试运行期间到店付款。请勿在聊天中发送银行卡信息。', 'booking.send': '发送预订请求', 'booking.check': '请检查预订信息', 'booking.checkBody': '请选择未来日期，并输入 1 到 30 之间的数值。', 'booking.sent': '请求已发送', 'booking.sentBody': '服务方接受后预订才会确认。', 'booking.failed': '预订失败',
  'trips.title': '行程', 'trips.loginCopy': '登录后查看预订。', 'trips.empty': '暂无行程。', 'trips.cancel': '取消预订', 'trips.cancelTitle': '取消预订？', 'trips.cancelBody': '服务方会收到通知。', 'trips.keep': '保留预订', 'trips.cancelFailed': '无法取消', 'trips.dateMissing': '日期不可用', 'payment.title': '付款', 'payment.arrival': '到店付款', 'payment.arrivalBody': '试运行期间不支持银行卡支付。服务方接受预订后再确认付款方式。', 'payment.protect': '保护付款信息', 'payment.protectBody': 'VenTour 绝不会在聊天中索要卡号、密码或验证码。', 'safety.title': '安全与紧急情况', 'safety.copy': '离开乌兰巴托前请保存这些号码。', 'safety.fire': '消防', 'safety.police': '警察', 'safety.ambulance': '急救', 'safety.call': '拨打', 'safety.offline': '可离线查看', 'safety.trip': '请把行程和服务方联系方式分享给信任的人。', 'common.back': '返回', 'common.cached': '正在显示已保存的数据，信息可能已过期。',
};

const ko = {
  'nav.explore': '둘러보기', 'nav.community': '커뮤니티', 'nav.trips': '여행', 'nav.inbox': '메시지', 'nav.profile': '프로필', 'welcome.title': '현지인의 시선으로\n몽골을 만나보세요', 'welcome.sub': '진짜 몽골을 발견하고 신뢰할 수 있는 현지 가이드와 여행하세요.', 'welcome.travel': '여행하기', 'welcome.travelSub': '숙소, 체험, 현지 가이드 찾기', 'welcome.guide': '가이드 되기', 'welcome.guideSub': '문화를 나누고 VenTour에서 수익 얻기',
  'auth.create': '계정 만들기', 'auth.welcome': '다시 오신 것을 환영합니다', 'auth.guide': '현지 가이드로 로그인', 'auth.traveler': '여행자로 계속', 'auth.name': '이름', 'auth.email': '이메일', 'auth.password': '비밀번호', 'auth.register': '가입', 'auth.login': '로그인', 'auth.hasAccount': '계정이 있나요? 로그인', 'auth.new': '처음이신가요? 가입하기',
  'profile.title': '프로필', 'profile.signInCopy': '로그인하여 여행과 가이드를 관리하세요.', 'profile.login': '로그인', 'profile.create': '계정 만들기', 'profile.account': '계정 설정', 'profile.saved': '저장한 여행', 'profile.payment': '결제', 'profile.help': '도움말', 'profile.safety': '안전 및 긴급상황', 'profile.becomeGuide': '가이드 되기', 'profile.guideWorkspace': '가이드 작업실', 'profile.ranking': '가이드 순위', 'profile.logout': '로그아웃',
  'booking.title': '예약 요청', 'booking.review': '서비스 제공자가 날짜와 요청을 확인한 후 예약이 확정됩니다.', 'booking.date': '날짜 (YYYY-MM-DD)', 'booking.time': '시작 시간 (24시간)', 'booking.hours': '시간', 'booking.nights': '박', 'booking.guests': '인원', 'booking.notes': '요청 사항 (선택)', 'booking.notesHint': '픽업, 식사 또는 접근성 요청', 'booking.rate': '요금', 'booking.total': '예상 합계', 'booking.pilot': '시범 운영 중에는 현장 결제입니다. 채팅으로 카드 정보를 보내지 마세요.', 'booking.send': '예약 요청 보내기', 'booking.check': '예약 정보를 확인하세요', 'booking.checkBody': '미래 날짜와 1~30 사이의 값을 입력하세요.', 'booking.sent': '요청을 보냈습니다', 'booking.sentBody': '서비스 제공자가 수락하면 예약이 확정됩니다.', 'booking.failed': '예약 실패',
  'trips.title': '여행', 'trips.loginCopy': '예약을 보려면 로그인하세요.', 'trips.empty': '아직 여행이 없습니다.', 'trips.cancel': '예약 취소', 'trips.cancelTitle': '예약을 취소할까요?', 'trips.cancelBody': '서비스 제공자에게 알림이 전송됩니다.', 'trips.keep': '예약 유지', 'trips.cancelFailed': '취소할 수 없습니다', 'trips.dateMissing': '날짜 없음', 'payment.title': '결제', 'payment.arrival': '현장 결제', 'payment.arrivalBody': '시범 운영 중에는 카드 결제를 지원하지 않습니다.', 'payment.protect': '결제 정보 보호', 'payment.protectBody': 'VenTour는 채팅에서 카드 번호, 비밀번호, 인증 코드를 요구하지 않습니다.', 'safety.title': '안전 및 긴급상황', 'safety.copy': '울란바토르를 떠나기 전에 이 번호를 저장하세요.', 'safety.fire': '소방', 'safety.police': '경찰', 'safety.ambulance': '구급차', 'safety.call': '전화', 'safety.offline': '오프라인 사용 가능', 'safety.trip': '신뢰하는 사람에게 일정과 가이드 연락처를 공유하세요.', 'common.back': '뒤로', 'common.cached': '저장된 정보를 표시합니다. 최신 정보가 아닐 수 있습니다.',
};

const ja = {
  'nav.explore': '探す', 'nav.community': 'コミュニティ', 'nav.trips': '旅行', 'nav.inbox': 'メッセージ', 'nav.profile': 'プロフィール', 'welcome.title': '現地の視点で\nモンゴルを発見', 'welcome.sub': '本物の場所を見つけ、信頼できる現地ガイドと旅しましょう。', 'welcome.travel': '旅行する', 'welcome.travelSub': '宿泊、体験、現地ガイドを探す', 'welcome.guide': 'ガイドになる', 'welcome.guideSub': '文化を共有し VenTour で収入を得る',
  'auth.create': 'アカウント作成', 'auth.welcome': 'おかえりなさい', 'auth.guide': '現地ガイドとしてログイン', 'auth.traveler': '旅行者として続ける', 'auth.name': '名前', 'auth.email': 'メール', 'auth.password': 'パスワード', 'auth.register': '登録', 'auth.login': 'ログイン', 'auth.hasAccount': 'アカウントをお持ちですか？ログイン', 'auth.new': '初めてですか？アカウント作成',
  'profile.title': 'プロフィール', 'profile.signInCopy': 'ログインして旅行とガイドを管理します。', 'profile.login': 'ログイン', 'profile.create': 'アカウント作成', 'profile.account': 'アカウント設定', 'profile.saved': '保存した旅行', 'profile.payment': '支払い', 'profile.help': 'ヘルプ', 'profile.safety': '安全と緊急時', 'profile.becomeGuide': 'ガイドになる', 'profile.guideWorkspace': 'ガイド管理', 'profile.ranking': 'ガイドランキング', 'profile.logout': 'ログアウト',
  'booking.title': '予約リクエスト', 'booking.review': '提供者が日付と内容を確認した後に予約が確定します。', 'booking.date': '日付 (YYYY-MM-DD)', 'booking.time': '開始時間 (24時間)', 'booking.hours': '時間', 'booking.nights': '泊', 'booking.guests': '人数', 'booking.notes': '提供者へのメモ（任意）', 'booking.notesHint': '送迎、食事、アクセシビリティの要望', 'booking.rate': '料金', 'booking.total': '見積合計', 'booking.pilot': '試験運用中は現地払いです。チャットでカード情報を送らないでください。', 'booking.send': '予約リクエストを送る', 'booking.check': '予約内容を確認してください', 'booking.checkBody': '未来の日付と1〜30の値を入力してください。', 'booking.sent': 'リクエスト送信済み', 'booking.sentBody': '提供者が承認すると予約が確定します。', 'booking.failed': '予約できませんでした',
  'trips.title': '旅行', 'trips.loginCopy': '予約を見るにはログインしてください。', 'trips.empty': '予約はまだありません。', 'trips.cancel': '予約をキャンセル', 'trips.cancelTitle': '予約をキャンセルしますか？', 'trips.cancelBody': '提供者に通知されます。', 'trips.keep': '予約を維持', 'trips.cancelFailed': 'キャンセルできませんでした', 'trips.dateMissing': '日付なし', 'payment.title': '支払い', 'payment.arrival': '現地払い', 'payment.arrivalBody': '試験運用中はカード決済を利用できません。', 'payment.protect': '支払い情報を保護', 'payment.protectBody': 'VenTour がチャットでカード番号、パスワード、確認コードを求めることはありません。', 'safety.title': '安全と緊急時', 'safety.copy': 'ウランバートルを離れる前に番号を保存してください。', 'safety.fire': '消防', 'safety.police': '警察', 'safety.ambulance': '救急車', 'safety.call': '電話', 'safety.offline': 'オフラインで利用可能', 'safety.trip': '旅程と提供者の連絡先を信頼できる人と共有してください。', 'common.back': '戻る', 'common.cached': '保存済み情報を表示中です。古い場合があります。',
};

const dictionaries = { en, mn, ru, zh, ko, ja };
const locales = { en: 'en-US', mn: 'mn-MN', ru: 'ru-RU', zh: 'zh-CN', ko: 'ko-KR', ja: 'ja-JP' };

export function useT() {
  const { language } = useAuth();
  const t = useCallback(
    (key) => String(dictionaries[language]?.[key] || en[key] || key).replaceAll('VenTour', 'ELCH'),
    [language],
  );
  return { t, language, locale: locales[language] || locales.en };
}

export function formatDateTime(value, language = 'en') {
  const date = value ? new Date(value) : null;
  if (!date || Number.isNaN(date.getTime())) return '';
  return new Intl.DateTimeFormat(locales[language] || locales.en, {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(date);
}

export function formatMoney(value, currency = 'USD', language = 'en') {
  return new Intl.NumberFormat(locales[language] || locales.en, {
    style: 'currency',
    currency,
  }).format(Number(value) || 0);
}
